name: CI/CD

on:
  push:
    branches: [Walid]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Clean up Docker Containers, Images, and Networks
        run: |
          docker rm -f backend frontend nginx db || true
          docker rmi backend frontend nginx || true
          docker network prune --force || true

      - name: Create Docker Network
        run: docker network create app_network || true

      - name: Pull Latest PostgreSQL Image
        run: docker pull postgres:13

      - name: Build Backend Image
        run: docker build -t backend ./backend

      - name: Build Frontend Image (Production)
        run: docker build --target production --build-arg REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }} -t frontend ./frontend

      - name: Build Nginx Image (Reverse Proxy)
        run: docker build -t nginx .

      - name: Run PostgreSQL Container
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: |
          docker run -d \
            --name db \
            --network app_network \
            -e POSTGRES_DB=${POSTGRES_DB} \
            -e POSTGRES_USER=${POSTGRES_USER} \
            -e POSTGRES_PASSWORD=${POSTGRES_PASSWORD} \
            -v pg_prod_data:/var/lib/postgresql/data \
            postgres:13

      - name: Run Backend Container
        env:
          APP_ENV: production
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          docker run -d \
            --name backend \
            --network app_network \
            -e APP_ENV=${APP_ENV} \
            -e SECRET_KEY=${SECRET_KEY} \
            -e DATABASE_URL=${DATABASE_URL} \
            backend

      - name: Run Frontend Container (Production)
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        run: |
          docker run -d \
            --name frontend \
            --network app_network \
            frontend

      - name: Run Nginx Container (Reverse Proxy)
        run: |
          docker run -d \
            --name nginx \
            --network app_network \
            -p 80:80 \
            nginx